spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hr?stringtype=unspecified
    username: hr
    password: 123

  mybatis-plus:
    configuration:
      # PostgreSQL ???????????????
      map-underscore-to-camel-case: true
      # ???? SQL????????????
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????
    type-aliases-package: cn.cloverclc.entity
logging:
  file:
    name: logs/running.log
  level:
    root: warn
    cn.cloverclc : info
server:
  port: 8080
